### PR TITLE
docs: Add clearer guide for statusline and tabuffline customization

### PR DESCRIPTION
**Pull request by LittleLegend-Pengiun**
As a new comer, I found the guide for `statusline` customization is really frustrating. The guide on the main docs is not clear, the guide from other members in the community is really outdated. It took me days before I found out the right way. 

In this PR, I separate the guide for `statusline` and `tabuffline`, also add example for each of them. This makes the guide clearer and easier to read and follow for new comers.

### CODE REVIEW

**Comment by siduck** [comment]
thats a lot of docs overload -_-

i dont think what can be confusing. the docs literally says statusline follows the same tabufliine syntax for overriding and you have to check  the order  in the src code files

**Comment by LittleLegend-Pengiun** [comment]
> thats a lot of docs overload -_-
> 
> i dont think what can be confusing. the docs literally says statusline follows the same tabufliine syntax for overriding and you have to check  the order  in the src code files

I think what's confusing here is the lack of example. So how about I reduce the amout of guide, but keep the 2 examples?

**Comment by siduck** [comment]
i dont think its confusing, the user just has to check the order on that src file

**Comment by LittleLegend-Pengiun** [comment]
> i dont think its confusing, the user just has to check the order on that src file

I mean, to some one work with Lua for a long time like you, it's not confusing at all. But isn't it better to at least, have a example for the new comers? I've reduce the amount of guide to be denser, so please have a look at that.

**Comment by siduck** [comment]
not quite, other new users could just override statusline just fine. you could just add a note to check the nvconfig.lua for default sets of options for statusline and then look at the stl/utils.lua for order

**Comment by LittleLegend-Pengiun** [comment]
> not quite, other new users could just override statusline just fine. you could just add a note to check the nvconfig.lua for default sets of options for statusline and then look at the stl/utils.lua for order.
> 
> I'm assuming you didnt read nvconfig file before, thats a must for any user as its the structure for chadrc, nvchad_ui docs are only for explanation of overriding those modules

Thanks for your comment! I've read the nvconfig.lua, but I only scan through it to config the nvdash. I'll update the guide soon.

**Review by siduck — APPROVED** [review]

**Pull request merged**
