### PR TITLE
Fix incorrect nesting in config documentation

### PR DESCRIPTION
**Pull request by mrassili**
the incorrect nesting in this doc might mislead other users, I had this issue because of it https://github.com/NvChad/NvChad/issues/531

Hope it helps others :)

### CODE REVIEW

**Comment by siduck76** [comment]
@mrassili oops sorry! does your issue get fixed by this? :D

**Comment by mrassili** [comment]
> @mrassili oops sorry! does your issue get fixed by this? :D

Yes it does :)

**Comment by mrassili** [comment]
Hello @siduck76 do you mind tagging the PR with `hacktoberfest-accepted` please?

**Comment by siduck76** [comment]
> Hello @siduck76 do you mind tagging the PR with `hacktoberfest-accepted` please?

how do i do that?

**Comment by G-Rowell** [comment]
Hey @mrassili 

Have you contributed to any other project in the past? (not just in this month).

We'd love some PRs that are not made for the sole intention of getting the Hacktoberfest badge,
we (and so many other maintainers on GitHub) become overwhelmed with so many small PRs during Hacktoberfest.



Galen

**Comment by mrassili** [comment]
Hey @G-Rowell 

Yes, I did contribute to OSS projects in the past outside this month (not only docs changes) (mainly to https://github.com/getferdi/ferdi, https://github.com/ejarzo/Shape-Your-Music, https://github.com/saferwall/saferwall …)

I would not say this PR was made for the sole intention of getting the Hacktoberfest badge, the main intention was to guide others who might have a hard time troubleshooting this issue https://github.com/NvChad/NvChad/issues/531
I do understand that you get overwhelmed with spam PRs during this month and I understand if you don't want to opt-in this repository :)

Marouane

**Comment by G-Rowell** [comment]
Given that you have made notable & extensive contributions to: https://github.com/saferwall/saferwall/commits?author=mrassili

I will create the label and add this to this PR.

I will however, caution you against such small contributions for your other Hacktoberfest PRs, as per: https://hacktoberfest.digitalocean.com/resources/qualitystandards 

---

Thank you for your contribution to this project, and the previous open source project you've supported.

My apologies if I have come off as rude.

---

Best wishes!
Galen

**Comment by siduck76** [comment]
@mrassili Im unable to make tsserver use null ls formatter by default , it keeps spamming this : 

image

**Pull request merged**
