### PR TITLE
Fixed indenting on lua code sections

### PR DESCRIPTION
**Pull request by primeapple**
Used 4 spaces for each indent :)

Thanks for your work!

### CODE REVIEW

**Comment by bryant-the-coder** [comment]
why 4 spaces?

**Comment by siduck** [comment]
@primeapple dont we use 2 spaces in nvchad's stylua config?

**Comment by bryant-the-coder** [comment]
> @primeapple dont we use 2 spaces in nvchad's stylua config?

that is what i m asking. cuz 2 spaces is easy to read lol

**Comment by primeapple** [comment]
I come from python and java, there everyone uses 4 spaces.

I'll refactor this to use 2 spaces only, if you want :)

**Comment by siduck** [comment]
as it was conflicting I closed the PR, @primeapple add a new one with 2 spaces

**Pull request closed without merging**
